# Generated by Django 4.0.3 on 2022-03-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_view_false_reviews', 'Может видеть все не модерированные отзывы')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
